-- MySQL Script generated by MySQL Workbench
-- Wed Aug  3 21:42:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema misur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema misur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `misur` DEFAULT CHARACTER SET utf8 ;
USE `misur` ;

-- -----------------------------------------------------
-- Table `misur`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `misur`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` INT NOT NULL,
  `existencia` INT NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `misur`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `misur`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `tipousuario` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) ,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `misur`.`ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `misur`.`ruta` (
  `idruta` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idzona` INT NOT NULL,
  `cantidadprod` INT NOT NULL,
  PRIMARY KEY (`idruta`),
  INDEX `fk_producto_ruta_idx` (`idproducto` ASC) ,
  INDEX `fk_ruta_usuario_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_ruta_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `misur`.`producto` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ruta_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `misur`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `misur`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `misur`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `idzona` INT NOT NULL,
  `comprasreal` VARCHAR(45) NOT NULL,
  `numerotel` BIGINT(10) NOT NULL,
  PRIMARY KEY (`idcliente`, `idzona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `misur`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `misur`.`zona` (
  `idzona` INT NOT NULL AUTO_INCREMENT,
  `nombrezona` VARCHAR(100) NOT NULL,
  `poblado` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idzona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `misur`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `misur`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  `cantidad` INT NOT NULL,
  `serieventa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_producto_idx` (`idproducto` ASC) ,
  INDEX `fk_venta_usuario_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_venta_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `misur`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `misur`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `misur`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `misur`.`permiso` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `misur`.`permiso_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `misur`.`permiso_usuario` (
  `idpermiso_perosna` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`idpermiso_perosna`),
  INDEX `fk_permiso_usuario_permiso_idx` (`idpermiso` ASC) ,
  CONSTRAINT `fk_permiso_usuario_permiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `misur`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
